#!/bin/bash
#
# Exemplos de uso da estrutura condicional case 
# para gerar um menu de opções em Shell Script

MENU="
[01]. Criar usuário          [06]. Atualizar repositóri
[02]. Criar senha            [07]. Instalar atualizações
[03]. Deletar usuário        [08]. Instalar openssh-server
[04]. Criar arquivo          [09]. Instalar squid e squid3
[05]. Criar pasta            [10]. Instalar sockes
"
echo "$MENU"
echo "----------------------"
read -p "Escolha uma opção do menu: " OPCAO
case "$OPCAO" in
        1)
            echo "Criando usuário..."
            read username
            $username 
        ;;

        2) 
            echo "Criando senha..."
            read password
            $password
        ;;

        3)
            echo "Deletando usuário..."
            read username
            $username

        ;;

        4)
            echo "Criando arquivo..."
            touch script3.txt
        ;;

        5)
            echo "Criando pasta..."
            mkdir pasta_de_Vanderlei
        ;;

        6)
            echo "Atualizando repositório no ubuntu..."
            apt-get update
        ;;

        7)
            echo "Instalando atualizações"
            apt-get upgrade -y
            clear
        ;;

        8) 
            echo "Instalando  Openssh-server"
            apt-get install openssh-server
            service ssh restart
        ;;

        9)  
            echo "Instalando squid3 e squid" 
            apt-get install squid3
        ;;

        10)
            echo "Instalando sockes"
        ;;

        *)  echo "Opção $OPCAO inválida!"
        exit 1
